#!/bin/bash

scp -r /home/hopper/github/f1tenth-course-labs/f1tenth_purepursuit  nvidia@100.93.242.50:~/catkin_ws/src/
# scp -r /home/hopper/github/f1tenth-course-labs/f1tenth_purepursuit/racelines  nvidia@100.93.242.50:~/catkin_ws/src/f1tenth_purepursuit
# scp -r /home/hopper/github/f1tenth-course-labs/f1tenth_purepursuit/src  nvidia@100.93.242.50:~/catkin_ws/src/f1tenth_purepursuit
# scp -r /home/hopper/github/f1tenth-course-labs/f1tenth_purepursuit/launch  nvidia@100.93.242.50:~/catkin_ws/src/f1tenth_purepursuit

# scp -r nvidia@100.93.242.50:~/catkin_ws/src/ /home/hopper/github/f1tenth-course-labs/f1tenth_purepursuit
# scp -r /home/hopper/github/f1tenth-course-labs/race/src/  nvidia@100.93.242.50:~/catkin_ws/src/race/src/

# scp -r  nvidia@100.93.242.50:~/depend_ws/src/F1tenth_car_workspace/base_mapping/map /home/hopper/github/f1tenth-course-labs/f1tenth_purepursuit